### ISSUE TITLE
Le module de géocodage inverse demande un paramètre searchGeometry 

### ISSUE THREAD

**Issue by guigzzzzzz** [IGNF/geoportal-sdk#101]
Bonjour,

Avec la version 3.2.18 de l'API Extension Geoportail OpenLayers, le module 'Gp.Services.reverseGeocode' nécessite un paramètre 'searchGeometry' qui est sensé être optionnel selon la doc du service.

## Votre environnement

* Version de l'API : 3.2.18
* Nom du navigateur et sa version : Firefox 107.0
* Operating System et sa version (desktop ou mobile) : Windows 10 desktop
* Lien eventuel vers votre projet :

## Type d'issue
[x] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

## Contexte

Je passe bien un lon et un lat dans mes appels, mais sans 'searchGeometry' ou avec un 'searchGeometry' à {}, j'obtiens l'erreur : 
`Uncaught Error: Parameter(s) 'searchGeometry' missing`

Doc du service 'reverse', param 'searchgeom' : "Ce paramètre n'est pas obligatoire pour des raisons de rétro-compatibilité. Si searchGeom n'est pas utilisé alors les paramètres lon et lat doivent l'être et on parle de point de recherche. "

Je suis passé de la version 3.2.14 à 3.2.18 de l'API JS.

## Pour les bugs : Etapes à suivre pour le reproduire

1. Implémenter une utilisation du module Gp.Services.reverseGeocode dans le code Javascript
2. Faire un appel avec lat et lon renseignés

## Comportement attendu

Le module 'Gp.Services.reverseGeocode' ne devrait pas nécessiter de paramètre 'searchGeometry' si lon et lat sont renseignés, comme auparavent

## Comportement actuel

Le module 'Gp.Services.reverseGeocode' nécessite un paramètre 'searchGeometry' dûment renseigné dans tous les cas

## Possible Cause/Correction/Solution technique (facultatif)

Dans le code de l'API : 
`if(t.serverUrl=t.serverUrl||"https://wxs.ign.fr/calcul/geoportail/geocodage/rest/0.1/reverse",T.apply(this,[t]),!t.searchGeometry)throw new Error(_.getMessage("PARAM_MISSING","searchGeometry"));`

**Comment by azarz** [comment]
Bonjour,

Corrigé ici : https://github.com/IGNF/geoportal-access-lib/pull/81
Ce sera disponible dans la prochaine release des extensions / du SDK

**Comment by elias75015** [comment]
Bonjour, 
le correctif est disponible dans la version 3.2.19 des extensions Géoportail pour Openlayers, et dans la version 3.3.20 du SDK Géoportail.

Je me permets donc de fermer, n'hésitez pas à rouvrir si le problème subsiste
