### ISSUE TITLE
le paramétrage du parser KML OL3 empêche l'affichage des labels des ponctuels

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#2]
Lorsqu'on ajoute une couche KML, on paramètre en dur le parser KML avec l'option showPointNames à false :

https://github.com/IGNF/geoportal-sdk/blob/master/src/ol3/OL3.js#L1650

cela empêche l'affichage des labels associés à des ponctuels, comme remarqué dans cette discussion du forum :

http://www.developpez.net/forums/d1617362/applications/sig-systeme-d-information-geographique/ign-api-geoportail/sdk-geoportail-couche-kml/#post8834264

Quelle est la raison de ce paramétrage ? Il faudrait dans tous les cas permettre de passer ce paramètre à true.

**Comment by lowzonenose** [comment]
En jouant avec le module CORS du navigateur, je récupère bien les _waypoints_ : 
![selection_075](https://cloud.githubusercontent.com/assets/10401006/21264668/aa2f550a-c39d-11e6-9a23-57815d18a742.png)

**Comment by gcebelieu** [comment]
OK ... il y a avait ça aussi... il faudrait que l'API puisse passer les bons paramètres CORS pour que les internautes n'aient pas besoin d'utiliser un module spécial du navigateur.

**Comment by lowzonenose** [comment]
:+1: affichage des labels associés à des ponctuels (au niveai des extensions) : 
cf. https://github.com/IGNF/geoportal-extensions/issues/98

**Comment by lowzonenose** [comment]
Mise en place de l'option '_showPointNames_' sur le format KML, ce qui permet d'afficher des labels associés à des ponctuels.
cf. https://github.com/IGNF/geoportal-sdk/commit/7ab96c20a9b6f252ddd039bc0f5649c457d89bdf
