### ISSUE TITLE
Rendre possible l'ajout / suppression de markers après création de la carte

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#23]
Le loader du SDK permet de positionner des markers sur la carte à l'initialisation. Cependant, une  fois la carte créée, il est impossible d'en rajouter de nouveaux, de les modifier ou de les supprimer.

Il faudrait, à l'instar des méthodes pour manipuler les controles et les layers  proposer des méthodes permettant de faire de même avec les markers. 

NB : à la différence des Layers et des Controls, il n'y a pas de notion d'identifiant  associé à un marker dans la propriété *markersOptions*. L'approche serait plutôt de proposer des getter et setter travaillant sur le tableau des markers : 

map.getMarkersOptions() : retourne un Array de Gp.MarkerOptions (ceux de la carte en cours)
map.setMarkersOptions(Array<Gp.MarkerOptions>) : remplace les markers de la carte par ceux passés en paramètres

**Comment by adpeyre** [comment]
Any update?

**Comment by elias75015** [comment]
#69 sur develop, dispo sur la 3.0.16. Je ferme
