### ISSUE TITLE
PB de compatibilité du controle GFI avec modifyControls

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#27]
* version 1.0.0 du SDK, 

* Exemple : samples/ol3/ol3-interaction.html

1. Cocher "enable feature selection" : la sélection des features fonctionne sur la carte :+1: 
2. Décocher "enable feature selection" : on ne peut plus sélectionner les features sur la carte (normal) mais le clic sur la carte provoque des erreurs dans la console : 

![error-clic](https://user-images.githubusercontent.com/8211614/34276288-fd714990-e6a0-11e7-9638-0e97756056c9.png)

3. Cocher a nouveau "enable feature selection" : la sélection des features ne fonctionne plus et on a la même erreur que précédemment dans la console

**Comment by pjjmunier** [comment]
Problème résolu au niveau des extensions -> modification de la méthode setMap afin de se désabonner des évènements lors de la suppression du contrôle (puisque lors d'un modifyControl les contrôle est supprimé puis ajouté)
