### ISSUE TITLE
SDK 3D - setXYCenter - proj4 undefined

### ISSUE THREAD

**Issue by elias75015** [IGNF/geoportal-sdk#30]
**Scenario :** 

- Charger la carte avec un centre qui a la propriété projection : 
```
Gp.Map.load(
"map",
{
...  
    center : {
             x : 6.242212,
             y : 44.811339,
             projection : "CRS:84"
         },
...
}
```
**Résultat :** 

Au chargement de la carte, on a l'erreur "proj4 is not defined". et le globe ne se charge pas.

![bug_proj4](https://user-images.githubusercontent.com/6764800/39829078-8acb365a-53bd-11e8-9d07-2f6c1b873b51.png)

**Cause :** 

Il semblerait que le changement sur la fonction setXYCenter de IT.js (lignes 701-710) y soit pour quelque chose (bien que ca ne marchait peut etre déjà pas avant) : b7bbd14c8da875a55d5abe814d0bb4a07963c9fb

![bug-proj4-git](https://user-images.githubusercontent.com/6764800/39829081-8ced2f1a-53bd-11e8-96bc-e675a51888a6.png)

**Comment by pjjmunier** [comment]
correction : proj4 -> Itowns.proj4
