### ISSUE TITLE
Disparition de l'image "closer" permettant de fermer les popups

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#31]
En utilisant le SDK 2D version 1.2.0, il semblerait qu’une image a disparu : la croix permettant de fermer les popups.
J’ai l’impression qu’elle a été oubliée dans le passage des images en base64 (Apparemment, le répertoire img/ ne fait plus partie du packaging du SDK 1.2) ?

![missing-popup](https://user-images.githubusercontent.com/8211614/39981977-1b2feb4e-5753-11e8-8e60-fdaef36da335.PNG)

![404-emeraud](https://user-images.githubusercontent.com/8211614/39981986-240502b8-5753-11e8-8635-c6384d84d23f.PNG)

**Comment by lowzonenose** [comment]
BUG résolu avec la  release 1.3.0 ...
