### ISSUE TITLE
Accès direct au sdk ne récupère pas itowns.js

### ISSUE THREAD

**Issue by elias75015** [IGNF/geoportal-sdk#32]
Si on fait : 

`<script src="https://ignf.github.io/geoportal-sdk/latest/dist/mixIt/GpOL3Itowns-src.js"></script>`

Comme indiqué dans le README : 

> Vous pouvez aussi choisir d’utiliser des fichiers hébergés en ligne, pour y accéder directement, lors de vos tests par exemple. Cependant, pour une utilisation en production, nous vous conseillons de télécharger ces fichiers et de les héberger vous-même, sur le même serveur qui héberge votre application.
Par exemple sur Github Pages :
http://ignf.github.io/geoportal-sdk/latest/dist/mixIt/GpOL3Itowns.js
http://ignf.github.io/geoportal-sdk/latest/dist/mixIt/GpOL3Itowns.css
http://ignf.github.io/geoportal-sdk/latest/dist/mixIt/GpOL3Itowns-src.js
http://ignf.github.io/geoportal-sdk/latest/dist/mixIt/GpOL3Itowns-src.css

On a en console : 
`http://localhost/api-v3-ahn-git/geoportal-sdk/dist/mixIt//itowns.js net::ERR_ABORTED`

Effectivement, le itowns.js distant n'est pas correctement récupéré

`https://ignf.github.io/geoportal-sdk/latest/dist/mixIt/itowns.js`

**Comment by lowzonenose** [comment]
Résolu dans la prochaine release...
