### ISSUE TITLE
PB chargement couche WFS avec le SDK version 1.2.0

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#34]
Cf. discussion sur le forum : https://www.developpez.net/forums/d1866592/applications/sig-systeme-d-information-geographique/ign-api-geoportail/pb-d-affichage-couches-wfs-sdk-1-2-0-a/

Je confirme le constat : 

la même configuration de layersOptions : 
```
layersOptions : {
                 "BDPARCELLAIRE-VECTEUR_WLD_BDD_WGS84G:commune" : {
                     format : "WFS",
                     url : "https://wxs.ign.fr/APIKEY/geoportail/wfs",
                     typeNames : "BDPARCELLAIRE-VECTEUR_WLD_BDD_WGS84G:commune"
                 },
}
```

Pour une couche WFS entraine un affichage avec le SDK 1.0.0 et pas avec la dernière version (1.2.0) du SDK.

Avec ce dernier, une requête est bien envoyée et le service répond mais pas d'affichage. On a le message suivant dans la console :

> AssertionError: Assertion failed. See https://openlayers.org/en/v4.6.5/doc/errors/#36 for details.

**Comment by lowzonenose** [comment]
Hummm, j'ai recompilé le SDK avec la version 4.0.1 d'*openlayer*, et ça fonctionne !?
L'**upgrade** *d'openlayers* en version 4.6.5 a produit quelques effets de bords...

**Comment by lowzonenose** [comment]
Implémentation du format GeoJSON d'openlayers de la méthode de lecture de la projection 

version 4.0.1 : 
Le type *EPSG* est géré...
```
ol.format.GeoJSON.prototype.readProjectionFromObject = function (object) {
        var geoJSONObject = object;
        var crs = geoJSONObject.crs;
        var projection;
        if (crs) {
            if (crs.type == 'name') {
                projection = ol.proj.get(crs.properties.name);
            } else if (crs.type == 'EPSG') {
                projection = ol.proj.get('EPSG:' + crs.properties.code);
            } else {
                ol.asserts.assert(false, 36);
            }
        } else {
            projection = this.defaultDataProjection;
        }
        return projection;
    };
```

version 4.6.5 : 
Oups, y'a plus de type *EPSG* !?

```
ol.format.GeoJSON.prototype.readProjectionFromObject = function (object) {
        var geoJSONObject = object;
        var crs = geoJSONObject.crs;
        var projection;
        if (crs) {
            if (crs.type == 'name') {
                projection = ol.proj.get(crs.properties.name);
            } else {
                ol.asserts.assert(false, 36);
            }
        } else {
            projection = this.defaultDataProjection;
        }
        return projection;
    };
```

**Comment by lowzonenose** [comment]
Arghhh..., je confirme que les autres formats de sortie ne fonctionnent
pas...

Le ven. 22 juin 2018 17:06, Gilles Cébélieu <notifications@github.com> a
écrit :

**Comment by gcebelieu** [comment]
Si, ça marche avec certaines valeurs, comme : "text/xml; subtype=gml/2.1.2".

Cf. https://github.com/IGNF/geoportal-sdk/blob/master/src/ol3/OL3.js#L1939-L1954

C'est assez crade ... je crois que c'est moi qui l'ai écrit ...

**Comment by lowzonenose** [comment]
Demande d'explication sur la modification de l’implémentation de la méthode de lecture de la projection du format GeoJSON (avec mon anglais de m...)  : 
https://github.com/openlayers/openlayers/issues/8306

**Comment by lowzonenose** [comment]
Pour info, 

Certain flux WFS renvoie en JSON l'information sur la projection suivante : 
`"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}}`
Et, OpenLayers gère correctement ce format.

Par contre, nos flux renvoient l'information suivante : 
`"crs":{"type":"EPSG","properties":{"code":"3857"}}`
Et, OpenLayers ne semble plus gérer ce format !?

**Comment by lowzonenose** [comment]
downgrade de la version d'OpenLayers, puis publication d'une release en attendant la modification des services WFS IGN...

**Comment by lowzonenose** [comment]
La release 1.3.0 permet d’utiliser de nouveau les flux WFS avec une sortie en GeoJSON.

Pour info,
L'*upgrade* d'OpenLayers (> 4.6.X) est prévue prochainement.
