### ISSUE TITLE
Externalisation de jaguarjs-jsdoc

### ISSUE THREAD

**Issue by pjjmunier** [IGNF/geoportal-sdk#36]
Actuellement jaguarjs-jsdoc est embarqué dans le code et modifié pour les besoins du projet.
L'objectif est de supprimer la copie (modifiée) de jaguarjs-jsdoc présente dans le code. L'installation de  jaguarjs-jsdoc et la modification de son code doit se faire lors du
> npm install

Les modifications identifiées de jaguarjs-jsdoc sont:
- la creation d'un fichier static/styles/sfc.css
- la modifications du fichier tmpl/layout.tmpl (import de sfc.css, ajout de headers...)
- l'ajout d'un dossier avec les images static/images

Les points durs relevés sont:
- configuration de jaguar (fichier jsdoc.json) pour obtenir le même rendu (theme?)
- la fonction GP.Map.load() n'apparaît pas dans l'index de la doc (l'interpretation du mot clé @module semble différente)

**Comment by lowzonenose** [comment]
Trop de modifications du code sur le projet *jaguarjs-jsdoc*.
Version embarquée trop ancienne  (5 ans) : 0.0.1 -  (latest : 1.1.0 - 2 ans).

**Comment by elias75015** [comment]
Je ferme --> Réfléchir à un nouveau template jsdoc.
