### ISSUE TITLE
Encapsulation de la barre de recherche dans une div externe ne fonctionne pas

### ISSUE THREAD

**Issue by frpan** [IGNF/geoportal-sdk#38]
Bonjour,
J'ai testé la config suivante pour ma map : 
_exemple complet ici : http://jsfiddle.net/a9Lhp3tz/522/_
```
controlsOptions: {
      "search": {
        div: "search",
        maximised: true
      }
```
avec le code html suivant : 
```
<div id="search"></div>
<div id="map"></div>
```
mais la barre de recherche s'affiche toujours dans la div "GPsearchEngine-*" créée par défaut

**Comment by lowzonenose** [comment]
Oui, je confirme !

**Comment by lowzonenose** [comment]
Fixé sur la branche **master**.
Les binaires sont disponibles : https://ignf.github.io/geoportal-sdk/current/SDK-2D/2d/GpSDK2D.js
En attente de **release**...
