### ISSUE TITLE
Erreur sur la version d'Openlayers

### ISSUE THREAD

**Issue by eldk** [IGNF/geoportal-sdk#40]
Bonjour,

N'y a t-il pas une erreur sur la version d'Openlayers : 

https://github.com/IGNF/geoportal-sdk/releases/tag/2.0.2

```
Version 2.0.2 des SDK 2D et 3D du Géoportail

    mise à jour de la version des extensions Géoportail en dépendances (requêtes https par défaut) :
        Extension Géoportail pour OpenLayers 2.1.2
```

4.4.2 ?

https://ignf.github.io/geoportal-sdk/latest/dist/2d/GpSDK2D.js

Cordialement,

Eric

**Comment by lowzonenose** [comment]
Bonjour,
la formulation prête à confusion..., c'est la version des _Extensions Geoportail_ qui est en 2.1.2, et non pas **OpenLayers**...
La version **d'OpenLayers** est bien en 4.4.2.
