### ISSUE TITLE
Dépendances manquantes?

### ISSUE THREAD

**Issue by adpeyre** [IGNF/geoportal-sdk#45]
Bonjour,

J'essaye d''ajouter @ignf-geoportal/sdk-2d avec npm mais  il semble qu'il manque des dépendances.

These relative modules were not found:

* ../package in ./node_modules/@ignf-geoportal/sdk-2d/src/SDK2D.js
* ../res/OpenLayers/OlMap.css in ./node_modules/@ignf-geoportal/sdk-2d/src/SDK2D.js

**Comment by lowzonenose** [comment]
Disponible sur la prochaine release

:ok: 
```
ERROR in ./node_modules/@ignf-geoportal/sdk-3d/src/SDK3D.js
Module not found: Error: Can't resolve '../package' in '/geoportal-third-party-integration/simple-map-SDK3D-es6-angular/node_modules/@ignf-geoportal/sdk-3d/src'
```
:ok: 
```
ERROR in ./node_modules/@ignf-geoportal/sdk-3d/src/SDK3D.js
Module not found: Error: Can't resolve '../res/Itowns/ItMap.css' in '/geoportal-third-party-integration/simple-map-SDK3D-es6-angular/node_modules/@ignf-geoportal/sdk-3d/src'
```
