### ISSUE TITLE
Affichage d'attributs non désirés dans les popups associées aux features

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-sdk#5]
Signalé sur le forum pour des fichiers KML :

https://www.developpez.net/forums/d1617362/applications/sig-systeme-d-information-geographique/ign-api-geoportail/sdk-geoportail-couche-kml/#post9009523

des attributs "styleUrl" sont affichés dans la popup alors qu'ils sont "internes" au format KML. Il ne faudrait pas les afficher dans les popups de features.

Je note aussi la présence systématique de l'attribut : "extensionsNode_ : undefined" pour les features des fichiers GPX.

Visible : 

* ici avec le SDK : http://jsfiddle.net/ignfgeoportail/4ekb5c41/embedded/result,js,html,css/ (attention utiliser le module CORS pour faire apparaitre la trace GPX)

* ici avec le portail :

https://www.geoportail.gouv.fr/carte?c=2.091951370239258,48.77734714570491&z=14&l0=ORTHOIMAGERY.ORTHOPHOTOS::GEOPORTAIL:OGC:WMTS(1)&d1=1369526(1)&permalink=yes

**Comment by gcebelieu** [comment]
@lowzonenose pourras-tu y jeter un oeil ?

**Comment by lowzonenose** [comment]
Sur le format KML, le propriété **styleUrl** est définie comme étant publique au même titre que les propriétés **geometry**, **name** et **description**...
Du coup, comme nous bouclons sur toutes les propriétés publiques pour l'affichage, on voit donc apparaître cet élément. 
Nous allons donc mettre une condition sur cette propriété...
